import { z } from "zod";

export const companies = [
  "Al Ameen bakery",
  "Al Ameen Restaurant",
  "Al Ameen water",
  "Al Ameen clinic",
  "Al Ameen building materials",
  "Al Ameen printing press",
  "Al Ameen Hotel",
  "Al Ameen Bank",
  "Alpha Industries",
  "Alpha Foods",
  "Alpha Logistics",
  "Alpha Labs",
  "Alpha Digital",
  "Alpha Energy",
  "Alpha Systems",
  "Beta Solutions",
  "Beta Foods",
  "Beta Tech",
  "Beta Motors",
  "Beta Electronics",
  "Beta Health",
  "Beta Global",
  "Beta Network",
  "Beta Vision",
  "Beta Innovations",
  "Beta Logistics",
  "Beta Energy",
  "Beta Media",
  "Beta Travel",
  "Beta Finance",
  "Charlie Ventures",
  "Charlie Foods",
  "Charlie Digital",
  "Charlie Health",
  "Charlie Systems",
  "Charlie Labs",
  "Charlie Media",
  "Charlie Innovations",
  "Charlie Logistics",
  "Charlie Motors",
  "Charlie Travel",
  "Charlie Finance",
  "Charlie Electric",
  "Charlie Network",
  "Charlie Energy",
  "Delta Technologies",
  "Delta Foods",
  "Delta Health",
  "Delta Digital",
  "Delta Global",
  "Delta Media",
  "Delta Logistics",
  "Delta Energy",
  "Delta Motors",
  "Delta Innovations",
  "Delta Vision",
  "Delta Travel",
  "Delta Finance",
  "Delta Network",
  "Delta Labs",
  "Echo Innovations",
  "Echo Foods",
  "Echo Digital",
  "Echo Labs",
  "Echo Health",
  "Echo Global",
  "Echo Motors",
  "Echo Travel",
  "Echo Finance",
  "Echo Network",
  "Echo Systems",
  "Echo Vision",
  "Echo Energy",
  "Echo Media",
  "Echo Logistics"
];

export type Company = typeof companies[number];

// User schema and types
export const userSchema = z.object({
  id: z.string(),
  username: z.string(),
  email: z.string().email(),
  createdAt: z.date().default(() => new Date()),
});

export const insertUserSchema = userSchema.omit({ id: true, createdAt: true });

export type User = z.infer<typeof userSchema>;
export type InsertUser = z.infer<typeof insertUserSchema>;
